name: app_data

version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: 0.5.3+4
  path_provider: 1.3.0
  google_sign_in: 4.0.7
  googleapis: 0.54.0
  googleapis_auth: 0.2.10
  moor_flutter: 2.0.0
  flutter_secure_storage: 3.3.1+1
  uuid: 2.0.2

  app_business:
    path: "../app_business"
  app_common:
    path: "../app_common"
  app_util:
    path: "../app_util"

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1
  pedantic: 1.8.0+1
  build_runner: ^1.6.5
  moor_generator: ^2.0.1
